add new functions like cloud-initto linux too make linux and mac more equal in layout and structure

diff --git a/Linux/flash b/Linux/flash
--- a/Linux/flash
+++ b/Linux/flash
@@ -21,14 +21,16 @@ usage: $0 [options] name-of-rpi.img
 Flash a local or remote Raspberry Pi SD card image.
 
 OPTIONS:
-  --help|-h      Show this message
-  --bootconf|-C  Copy this config file to /boot/config.txt
-  --config|-c    Copy this config file to /boot/device-init.yaml (or occidentalis.txt)
-  --hostname|-n  Set hostname for this SD image
-  --ssid|-s      Set WiFi SSID for this SD image
-  --password|-p  Set WiFI password for this SD image
+  --help|-h       Show this message
+  --bootconf|-C   Copy this config file to /boot/config.txt
+  --config|-c     Copy this config file to /boot/device-init.yaml (or occidentalis.txt)
+  --hostname|-n   Set hostname for this SD image
+  --ssid|-s       Set WiFi SSID for this SD image
+  --password|-p   Set WiFI password for this SD image
   --clusterlab|-l Start Cluster-Lab on boot: true or false
-  --device|-d    Card Device
+  --device|-d     Choose device to flash to (e.g. 'sdb' for /dev/sdb)
+  --userdata|-u   Copy this cloud-init file to /boot/user-data
+  --metadata|-m   Copy this cloud-init file to /boot/meta-data
 
 For HypriotOS devices:
 
@@ -70,16 +72,18 @@ fi
 for arg
 do
   delim=""
-  case "$arg" in
+  case "${arg}" in
     --help) args="${args}-h ";;
     --verbose) args="${args}-v ";;
     --config) args="${args}-c ";;
     --hostname) args="${args}-n ";;
     --ssid) args="${args}-s ";;
     --password) args="${args}-p ";;
-    --device) args="${args}-d ";;
     --bootconf) args="${args}-C ";;
     --clusterlab) args="${args}-l ";;
+    --device) args="${args}-d ";;
+    --userdata) args="${args}-u ";;
+    --metadata) args="${args}-m ";;
     # pass through anything else
     *) [[ "${arg:0:1}" == "-" ]] || delim="\""
       args="${args}${delim}${arg}${delim} ";;
@@ -88,7 +92,7 @@ done
 # reset the translated args
 eval set -- "$args"
 # now we can process with getopt
-while getopts "hc:n:s:p:d:C:l:" opt; do
+while getopts ":hc:n:s:p:C:l:d:u:m:" opt; do
   case $opt in
     h)  usage ;;
     c)  CONFIG_FILE=$OPTARG ;;
@@ -97,12 +101,14 @@ while getopts "hc:n:s:p:d:C:l:" opt; do
     s)  WIFI_SSID=$OPTARG ;;
     p)  WIFI_PASSWORD=$OPTARG ;;
     l)  CLUSTERLAB=$OPTARG ;;
-    d)  disk=$OPTARG ;;
+    d)  DEVICE=$OPTARG ;;
+    u)  USER_DATA=$OPTARG ;;
+    m)  META_DATA=$OPTARG ;;
     \?) usage ;;
     :)
       echo "option -$OPTARG requires an argument"
       usage
-      ;;
+    ;;
   esac
 done
 shift $((OPTIND -1))
@@ -122,6 +128,34 @@ image=$1
 filename=$(basename "${image}")
 extension="${filename##*.}"
 filename="${filename%.*}"
+
+if [ ! -z "${USER_DATA}" ]; then
+  if [ ! -f "${USER_DATA}" ]; then
+    echo "Cloud-init file ${USER_DATA} not found!"
+    exit 10
+  fi
+fi
+
+if [ ! -z "${META_DATA}" ]; then
+  if [ ! -f "${META_DATA}" ]; then
+    echo "Cloud-init file ${META_DATA} not found!"
+    exit 10
+  fi
+fi
+
+if [ ! -z "${BOOT_CONF}" ]; then
+  if [ ! -f "${BOOT_CONF}" ]; then
+    echo "File ${BOOT_CONF} not found!"
+    exit 10
+  fi
+fi
+
+if [ ! -z "${CONFIG_FILE}" ]; then
+  if [ ! -f "${CONFIG_FILE}" ]; then
+    echo "File ${CONFIG_FILE} not found!"
+    exit 10
+  fi
+fi
 
 if [ -f "/tmp/${filename}" ]; then
   image=/tmp/${filename}
@@ -183,7 +217,7 @@ while true; do
   else
     df -h
   fi
-
+  disk="$DEVICE"
   if [[ -z "${disk}" ]]; then
     read -p "Please pick your device: "
     disk="${REPLY}"
@@ -248,20 +282,31 @@ echo "Mounting ${dev} to customize..."
 FS_TYPE=$(sudo blkid -o value -s TYPE "${dev}" || echo vfat)
 sudo mount -t ${FS_TYPE} "${dev}" "${boot}"
 
-if [ -f "${CONFIG_FILE}" ]; then
-  if [[ "${CONFIG_FILE}" == *"occi"* ]]; then
-    echo "Copying ${CONFIG_FILE} to ${boot}/occidentalis.txt ..."
-    sudo cp "${CONFIG_FILE}"  "${boot}/occidentalis.txt"
-  else
-    echo "Copying ${CONFIG_FILE} to ${boot}/device-init.yaml ..."
-    sudo cp "${CONFIG_FILE}"  "${boot}/device-init.yaml"
+ if [ -f "${CONFIG_FILE}" ]; then
+    if [[ "${CONFIG_FILE}" == *"occi"* ]]; then
+      echo "Copying ${CONFIG_FILE} to ${boot}/occidentalis.txt ..."
+      cp "${CONFIG_FILE}"  "${boot}/occidentalis.txt"
+    else
+      echo "Copying ${CONFIG_FILE} to ${boot}/device-init.yaml ..."
+      cp "${CONFIG_FILE}"  "${boot}/device-init.yaml"
+    fi
   fi
-fi
 
-if [[ -f "${BOOT_CONF}" ]]; then
-  echo "Copying ${BOOT_CONF} to ${boot}/config.txt ..."
-  sudo cp "${BOOT_CONF}" "${boot}/config.txt"
-fi
+  if [[ -f "${BOOT_CONF}" ]]; then
+    echo "Copying ${BOOT_CONF} to ${boot}/config.txt ..."
+    sudo cp "${BOOT_CONF}" "${boot}/config.txt"
+  fi
+
+  if [ -f "${USER_DATA}" ]; then
+    echo "Copying cloud-init ${USER_DATA} to ${boot}/user-data ..."
+    sudo cp "${USER_DATA}" "${boot}/user-data"
+  fi
+
+  if [ -f "${META_DATA}" ]; then
+    echo "Copying cloud-init ${META_DATA} to ${boot}/meta-data ..."
+    sudo cp "${META_DATA}" "${boot}/meta-data"
+  fi
+
 
 if [ -f "${boot}/device-init.yaml" ]; then
   echo "Setting device-init"
@@ -285,6 +330,18 @@ if [ -f "${boot}/device-init.yaml" ]; then
   fi
 fi
 
+ # cloud-init
+  if [ -f "${boot}/user-data" ]; then
+    if [ ! -z "${SD_HOSTNAME}" ]; then
+      echo "Set hostname=${SD_HOSTNAME}"
+      sudo sed -i -e "s/.*hostname:.*\$/hostname: ${SD_HOSTNAME}/" "${boot}/user-data"
+    fi
+
+    if [ ! -f "${boot}/meta-data" ]; then
+      echo "Creating empty meta-data"
+      sudo touch "${boot}/meta-data"
+    fi
+  fi
 # legacy: /boot/occidentalis.txt of old Hector release
 if [ -f "${boot}/occidentalis.txt" ]; then
   echo "Setting Occidentalis"
@@ -293,11 +350,11 @@ if [ -f "${boot}/occidentalis.txt" ]; then
     sudo sed -i -e "s/.*hostname.*=.*\$/hostname=${SD_HOSTNAME}/" "${boot}/occidentalis.txt"
   fi
   if [ ! -z "${WIFI_SSID}" ]; then
-    echo "  Set wifi_ssid=${WIFI_SSID}"
+    echo "Set wifi_ssid=${WIFI_SSID}"
     sudo sed -i -e "s/.*wifi_ssid.*=.*\$/wifi_ssid=${WIFI_SSID}/" "${boot}/occidentalis.txt"
   fi
   if [ ! -z "${WIFI_PASSWORD}" ]; then
-    echo "  Set wifi_password=${WIFI_PASSWORD}"
+    echo "Set wifi_password=${WIFI_PASSWORD}"
     sudo sed -i -e "s/.*wifi_password.*=.*\$/wifi_password=${WIFI_PASSWORD}/" "${boot}/occidentalis.txt"
   fi
 fi
